# Generated by Django 4.2.7 on 2023-11-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(default=0.0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
                ('category', models.CharField(choices=[('N', 'Nourriture'), ('V', 'Vêtement'), ('EN', 'Entretien'), ('J', 'Jouet'), ('A', 'Autre')], default=None, max_length=2)),
            ],
        ),
    ]
