# Generated by Django 4.2.7 on 2023-11-14 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_promo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promotion_start_date', models.DateField()),
                ('promotion_end_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='store.product')),
            ],
        ),
    ]
