# Generated by Django 4.2.7 on 2023-11-16 00:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_promotion_product_promotion_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='pourcentage_promo',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
