# Generated by Django 4.2.7 on 2023-11-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_promotion_pourcentage_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_active',
            field=models.BooleanField(default=False),
        ),
    ]
