# Generated by Django 4.2.7 on 2023-11-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_promotion_promotion_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='promotion_active',
        ),
    ]
